sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tN5GMEgw78sB2vGd2cZ
    access-key-secret: BmIdA8ubiqxn9zadtOp2gkHmxh1zyL
    bucket-name: sky-take-out-single
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2