sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tN5GMEgw78sB2vGd2cZ
    access-key-secret: BmIdA8ubiqxn9zadtOp2gkHmxh1zyL
    bucket-name: sky-take-out-single
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2
  wechat:
    appid: wxcb905e8be256c849
    secret: dbfa06a924c44e520154d81b6613d489
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://428af860.r28.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php